# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${API_DB_URL:jdbc:mysql://localhost:3306/api}
    username: ${API_DB_USERNAME:root}
    password: ${API_DB_PASSWORD:Wei.1234}
